(cl:defpackage arduinobot_remote-msg
  (:use )
  (:export
   "<ARDUINOBOTTASKACTION>"
   "ARDUINOBOTTASKACTION"
   "<ARDUINOBOTTASKACTIONFEEDBACK>"
   "ARDUINOBOTTASKACTIONFEEDBACK"
   "<ARDUINOBOTTASKACTIONGOAL>"
   "ARDUINOBOTTASKACTIONGOAL"
   "<ARDUINOBOTTASKACTIONRESULT>"
   "ARDUINOBOTTASKACTIONRESULT"
   "<ARDUINOBOTTASKFEEDBACK>"
   "ARDUINOBOTTASKFEEDBACK"
   "<ARDUINOBOTTASKGOAL>"
   "ARDUINOBOTTASKGOAL"
   "<ARDUINOBOTTASKRESULT>"
   "ARDUINOBOTTASKRESULT"
  ))

